---
apiVersion: v1
kind: Pod
metadata:
  labels:
    application: jenkins-slave
spec:
  containers:
  - name: dnd
    image: docker:stable-dind
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 10m
        memory: 128Mi
    securityContext:
        privileged: true
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: dockersock
      readOnly: false
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock

